version: '3.9'

services:
  mysql:
    build:
      context: ./database
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "./database/migrations:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
    ports:
      # - "3306:3306"
      - "3307:3306"
      - "33070:33060"
