version: '3.9'

services:
  mysql:
    build:
      context: ./
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
